### ISSUE TITLE
Running gosec ./... misses everything but one file, then exits

### ISSUE THREAD

**Issue by tcpiplab** [securego/gosec#336] opened 2019-07-10 10:06 UTC
### Summary
When I run `gosec ./...` inside a directory containing a file named `main.go`, and containing sub-directories containing other `.go` files, only one of the files (`models/talk.go`) is checked.

### Steps to reproduce the behavior
Run `gosec ./...` inside a directory containing `.go` files and sub-directories containing `.go` files. This is the output:
```
user123@Kali-laptop:~/Repos/talker/Auth/src/some-golang$ ~/go/bin/gosec ./...
[gosec] 2019/07/10 02:29:38 Including rules: default
[gosec] 2019/07/10 02:29:38 Excluding rules: default
[gosec] 2019/07/10 02:29:38 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/routers
[gosec] 2019/07/10 02:29:38 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/tests
[gosec] 2019/07/10 02:29:38 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/validator
[gosec] 2019/07/10 02:29:38 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/controllers
[gosec] 2019/07/10 02:29:38 Import directory: /home/user123/Repos/talker/Auth/src/some-golang
[gosec] 2019/07/10 02:29:38 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/models
[gosec] 2019/07/10 02:29:38 Checking package: models
[gosec] 2019/07/10 02:29:38 Checking file: /home/user123/Repos/talker/Auth/src/some-golang/models/talk.go
Results:


Summary:
   Files: 1
   Lines: 18
   Nosec: 0
  Issues: 0
```

But you can see that `main.go` was missed and several other `.go` files that were missed in the sub-directories:
```shell
user123@Kali-laptop:~/Repos/talker/Auth/src/some-golang$ find . -name "*.go"
./main.go
./tests/default_test.go
./validator/validator.go
./routers/router.go
./models/talk.go
./controllers/talk.go
./controllers/default.go
./controllers/auth.go

```
### gosec version
The `-version` output is empty:
```shell
$ ~/go/bin/gosec -version
Version:
Git tag:
Build date:
```

### Go version
```shell
$ go version
go version go1.11.6 linux/amd64
```

### Operating system / Environment
```shell
$ uname -a
Linux Kali-laptop 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-5kali1 (2019-06-20) x86_64 GNU/Linux
```

### Expected behavior
Checking each `.go` file in the working directory and in each sub-directory.

### Actual behavior
Checking only one file and exiting.

**Comment by gcmurphy** [comment] 2019-07-10 17:55
Is `GO111MODULE=on` set in your environment?

**Comment by tcpiplab** [comment] 2019-07-10 20:36
Thank you so much for your quick response.

It was not set in my environment. But after doing this: `export GO111MODULE=on` and running `~/go/bin/gosec ./...` I'm now getting lots of debug output, a few Golang errors, and some of the expected `gosec` output. 

But instead of pasting those 200 lines of output, I have a theory: maybe my installation of `gosec` is the problem. I installed it with `go get github.com/securego/gosec/cmd/gosec`, rather than the more thorough `make`/`make test` method described in the [Development](https://github.com/securego/gosec/blob/master/README.md#development) section of the README file. I'll try that and get back to you.

**Comment by gcmurphy** [comment] 2019-07-11 00:15
You could also try one of the [releases](https://github.com/securego/gosec/releases), but it should work via `go get github.com/securego/gosec/cmd/gosec`. 

The errors could be actual compile errors in your project. Maybe also double check that you can build the project you're trying to scan.

**Comment by tcpiplab** [comment] 2019-07-11 17:01
Thank you. It turned out that the solution to all the problems was to clone the repository into a directory outside (above) my `$GOPATH` and then build it from there. 


You may close this ticket.

**Comment by tcpiplab** [comment] 2019-07-11 17:37
The above solution got me to a successful installation of `gosec`, but it looks like it is still not checking two of my eight files. In the Summary output below, it says `Files: 15`. But only six of what it checked are my files. The other nine are `gosec` files:
```shell
user123@Kali-laptop:~/Repos/gosec$ sudo ./gosec ../talker/Auth/src/some-golang/...
[gosec] 2019/07/11 09:49:09 Including rules: default
[gosec] 2019/07/11 09:49:09 Excluding rules: default
[gosec] 2019/07/11 09:49:09 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/validator
[gosec] 2019/07/11 09:49:19 Checking package: validator
[gosec] 2019/07/11 09:49:19 Checking file: /home/user123/Repos/talker/Auth/src/some-golang/validator/validator.go
[gosec] 2019/07/11 09:49:19 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/controllers
[gosec] 2019/07/11 09:49:58 Checking package: controllers
[gosec] 2019/07/11 09:49:58 Checking file: /home/user123/Repos/talker/Auth/src/some-golang/controllers/auth.go
[gosec] 2019/07/11 09:49:58 Checking file: /home/user123/Repos/talker/Auth/src/some-golang/controllers/talk.go
[gosec] 2019/07/11 09:49:58 Checking file: /home/user123/Repos/talker/Auth/src/some-golang/controllers/default.go
[gosec] 2019/07/11 09:49:58 Import directory: /home/user123/Repos/talker/Auth/src/some-golang
[gosec] 2019/07/11 09:49:58 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/models
[gosec] 2019/07/11 09:49:58 Checking package: models
[gosec] 2019/07/11 09:49:58 Checking file: /home/user123/Repos/talker/Auth/src/some-golang/models/talk.go
[gosec] 2019/07/11 09:49:58 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/routers
[gosec] 2019/07/11 09:50:00 Checking package: routers
[gosec] 2019/07/11 09:50:00 Checking file: /home/user123/Repos/talker/Auth/src/some-golang/routers/router.go
[gosec] 2019/07/11 09:50:00 Import directory: /home/user123/Repos/talker/Auth/src/some-golang/tests
[gosec] 2019/07/11 09:50:02 Checking package: gosec
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/analyzer.go
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/call_list.go
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/config.go
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/errors.go
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/helpers.go
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/import_tracker.go
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/issue.go
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/resolve.go
[gosec] 2019/07/11 09:50:02 Checking file: /home/user123/Repos/gosec/rule.go
Results:

Golang errors in file: [/home/user123/Repos/talker/Auth/src/some-golang/controllers/auth.go]:
  > [line 4 : column 2] - could not import some-golang/validator (invalid package name: "")

Golang errors in file: [/home/user123/Repos/talker/Auth/src/some-golang/controllers/talk.go]:
  > [line 6 : column 2] - could not import some-golang/models (invalid package name: "")

Golang errors in file: [/home/user123/Repos/talker/Auth/src/some-golang/routers/router.go]:
  > [line 4 : column 2] - could not import some-golang/controllers (invalid package name: "")

[/home/user123/Repos/talker/Auth/src/some-golang/validator/validator.go:56] - G304: Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
  > ioutil.ReadFile(PrivateKeyAbsPath)

[/home/user123/Repos/talker/Auth/src/some-golang/validator/validator.go:60] - G304: Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
  > ioutil.ReadFile(PublicKeyAbsPath)

[/home/user123/Repos/talker/Auth/src/some-golang/controllers/talk.go:125] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > json.Unmarshal(body, &response)

Summary:
   Files: 15
   Lines: 1583
   Nosec: 4
  Issues: 3
```
Here you can see the list of all eight of my `.go` files. The first two were not checked: `main.go` and `tests/default_test.go`.
```shell
user123@Kali-laptop:~/Repos/gosec$ find ../talker/ -name "*.go"
../talker/Auth/src/some-golang/main.go
../talker/Auth/src/some-golang/tests/default_test.go
../talker/Auth/src/some-golang/validator/validator.go
../talker/Auth/src/some-golang/routers/router.go
../talker/Auth/src/some-golang/models/talk.go
../talker/Auth/src/some-golang/controllers/talk.go
../talker/Auth/src/some-golang/controllers/default.go
../talker/Auth/src/some-golang/controllers/auth.go
```

**Comment by gcmurphy** [comment] 2019-07-11 23:46
I see that you invoked gosec via `sudo` I think the `export GO111MODULE=on` environment variable would've been scrubbed from the environment in that case. 

Test files will not be checked  unless you add the -test flag. By default we ignore test cases and vendor files. However I would expect `main.go` to be checked.

**Comment by tcpiplab** [comment] 2019-07-12 00:47
Thank you @gcmurphy. In fact I get the same results without prepending `sudo`. Still the `main.go` and `tests/default_tests.go` files are missed. I tried the `-tests` flag, which did not change anything. I'm OK skipping the tests. But I wonder what is causing it to skip `main.go`. Do I need to somehow specify a package to contain `main.go` or something?

**Comment by ccojocar** [comment] 2019-09-03 09:40
How does your `main.go` looks like? Please can you provide its content? is it possible to attached the entire project as an archive?

**Comment by ccojocar** [comment] 2019-09-10 07:36
@tcpiplab I am going to close this because I cannot reproduce it due to the lack of samples. Please feel free to open another issue if you are still facing the problem, and please attach a sample which can be used to reproduce the bug. Thanks!

**Closed by ccojocar** 2019-09-10 07:36 UTC
