### ISSUE TITLE
v2.1.0 release linux tarball broken?

### ISSUE THREAD

**Issue by castlemilk** [securego/gosec#416] opened 2019-11-28 22:49 UTC
### Summary 

Attempting to extract the contents of the https://github.com/securego/gosec/releases/download/v2.1.0/gosec_2.1.0_linux_amd64.tar.gz tarball results in the following:

```bash
$ tar -xzf gosec_2.1.0_linux_amd64.tar.gz
tar: unexpected end of file
tar: short read
```

the `gosec` binary then gives me a segfault when trying to use

### Steps to reproduce the behavior

1. download binary for v2.1.0 release
2. attempt to untar (should report some errors and may unpack the gosec binary)
3. attempt to run the gosec binary with say `gosec version`

### gosec version

v2.1.0

### Go version (output of 'go version')

v1.13

### Operating system / Environment

linux amd64

### Expected behavior

* linux tarball should be extractable without errors like in 2.0.0
* gosec binary should work for linux

### Actual behavior

gosec binary doesnt work on linux

**Comment by gcmurphy** [comment] 2019-12-17 01:44
I cannot reproduce this locally.  Please retry download and verify the checksum of the downloaded binary. I'm closing for now. Re-open if this problem persists.

```
$ file gosec_2.1.0_linux_amd64.tar.gz 
gosec_2.1.0_linux_amd64.tar.gz: gzip compressed data, original size modulo 2^32 8928256
$ sha256sum gosec_2.1.0_linux_amd64.tar.gz 
9b6e0b71b86cc79844e4c519b6d3c73701d2b71f4fd80f3b97aad93af7cb0b0e  gosec_2.1.0_linux_amd64.tar.gz
grant@thinkpad:~/src/github.com/securego/tmp$ tar xf gosec_2.1.0_linux_amd64.tar.gz 
grant@thinkpad:~/src/github.com/securego/tmp$ ls -l
total 13380
-rwxr-xr-x 1 grant grant 8906987 Oct 10 00:09 gosec
-rw-r--r-- 1 grant grant 4766964 Dec 17 11:33 gosec_2.1.0_linux_amd64.tar.gz
-rw-r--r-- 1 grant grant    9138 Jul 27  2018 LICENSE.txt
-rw-r--r-- 1 grant grant    9176 Oct 10 00:06 README.md
grant@thinkpad:~/src/github.com/securego/tmp$ ./gosec
```

**Closed by gcmurphy** 2019-12-17 01:44 UTC
