### ISSUE TITLE
SIGSEGV running `gosec ./...`

### ISSUE THREAD

**Issue by estensen** [securego/gosec#419] opened 2019-12-09 09:18 UTC
### Summary
Running `gosec ./...` causes SIGSEGV when gosec isn't installed as a project dependency.

### Steps to reproduce the behavior
```
Install gosec outside the project directory
$ go get github.com/securego/gosec/cmd/gosec

$ cd <project>
$ gosec ./...
[gosec] 2019/12/09 09:59:54 Including rules: default
[gosec] 2019/12/09 09:59:54 Excluding rules: default
[gosec] 2019/12/09 09:59:54 Import directory: <masked>
[gosec] 2019/12/09 09:59:54 Checking package: <masked>
[gosec] 2019/12/09 09:59:54 Checking file: <masked>
[gosec] 2019/12/09 09:59:54 Checking file: <masked>
[gosec] 2019/12/09 09:59:54 Checking file: <masked>
[gosec] 2019/12/09 09:59:54 Checking file: <masked>
[gosec] 2019/12/09 09:59:54 Checking file: <masked>
[gosec] 2019/12/09 09:59:54 Checking file: <masked>
[gosec] 2019/12/09 09:59:54 Checking file: <masked>
[gosec] 2019/12/09 09:59:54 Checking file: <masked>
[gosec] 2019/12/09 09:59:54 Import directory: <masked>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12482b2]

goroutine 55 [running]:
golang.org/x/tools/go/packages.(*loader).loadRecursive(0xc000654000, 0x0)
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:678 +0x22
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0xc000654000, 0xc0005ca590, 0x0)
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:685 +0x35
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:684 +0x13f
```

Running it again I get SIGSEGV importing a different directory

```
gosec ./...
[gosec] 2019/12/09 10:10:18 Including rules: default
[gosec] 2019/12/09 10:10:18 Excluding rules: default
[gosec] 2019/12/09 10:10:18 Import directory: <masked>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12482b2]

goroutine 107 [running]:
golang.org/x/tools/go/packages.(*loader).loadRecursive(0xc0000e8420, 0x0)
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:678 +0x22
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0xc0000e8420, 0xc00043e010, 0x0)
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:685 +0x35
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:684 +0x13f
```

Installing gosec to the project fixes the problem.
Could this be an issue with my GOPATH?

### gosec version
No version?!
```
gosec --version
Version:
Git tag:
Build date:
```

### Go version (output of 'go version')
go version go1.13.4 darwin/amd64

### Operating system / Environment
macOS Catalina

**Comment by wavded** [comment] 2019-12-09 13:28
Same issue

**Comment by gcmurphy** [comment] 2019-12-17 01:50
Can you please provide details on: 

- Is $GOPATH set? If so what to?
- Is $GO111MODULE set? If so what to?
- Git head: `cd ~/go/src/github.com/securego/gosec && git rev-parse HEAD`
- Can you reproduce the sigsegv with a small isolated example program? 
- Is there information in the stacktrace produced that shows where exactly the entrypoint from gosec is? (e.g. `cated by github.com/securego/gosec/....`).

**Comment by estensen** [comment] 2019-12-17 10:50
$GOPATH
/Users/havard.anda.estensen/go

$GO111MODULE is not set

Git head
df484bfa9e9ff3f34e09869a289d1568f2ee4e90

```
➜ hello tree .
.
└── main.go
```

```
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

```
➜ hello gosec ./...
[gosec] 2019/12/17 11:48:06 Including rules: default
[gosec] 2019/12/17 11:48:06 Excluding rules: default
[gosec] 2019/12/17 11:48:06 Import directory: /Users/havard.anda.estensen/Developer/tmp/hello
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12482b2]

goroutine 30 [running]:
golang.org/x/tools/go/packages.(*loader).loadRecursive(0xc0000cc370, 0x0)
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:678 +0x22
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0xc0000cc370, 0xc0003cf110, 0x0)
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:685 +0x35
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1
	/Users/havard.anda.estensen/go/src/golang.org/x/tools/go/packages/packages.go:684 +0x13f
```

**Comment by ccojocar** [comment] 2020-01-02 17:12
Can you try to set GO111MODULE and then run `go mod init` in the hello folder?

**Comment by ccojocar** [comment] 2020-01-06 09:04
I am not able to reproduce the crash with latest version from master just following your steps:

```
$ go version
go version go1.13.5 darwin/amd64
$ export GO111MODULE=off
$ gosec ./...
[gosec] 2020/01/06 10:02:59 Including rules: default
[gosec] 2020/01/06 10:02:59 Excluding rules: default
[gosec] 2020/01/06 10:02:59 Import directory: /Users/cosmin/projects/test-gosec
[gosec] 2020/01/06 10:03:00 Checking package: main
[gosec] 2020/01/06 10:03:00 Checking file: /Users/cosmin/projects/test-gosec/main.go
Results:


Summary:
   Files: 1
   Lines: 7
   Nosec: 0
  Issues: 0
```

**Comment by ccojocar** [comment] 2020-01-06 09:05
I am going to close this issue. Please fell free to open another issue if you encounter again this problem.  Also make sure that `go build` works properly. Thanks!

**Closed by ccojocar** 2020-01-06 09:05 UTC

**Comment by estensen** [comment] 2020-01-06 10:15
Both `GO111MODULE=off` and `GO111MODULE=on`+ running `go mod init` yields the same error.
Haven't had any problems with `go build`.

**Comment by ccojocar** [comment] 2020-01-06 10:29
Do you use the latest `gosec` from master? See above, I tried to reproduce it but I couldn't. Maybe I'm missing something but I created the same hello world file outside of GOPATH as you mentioned in the bug description, and then I just run gosec against it.

**Comment by estensen** [comment] 2020-01-06 10:34
Fetched latest `gosec` from master and it now works. Thanks for you help!
