### ISSUE TITLE
Major slowdown and memory usage increase in commit 85d180848dbb8f86cba5d71bbbe06e1b40ce2705

### ISSUE THREAD

**Issue by MrJoy** [securego/gosec#303] opened 2019-04-26 00:37 UTC
### Summary 

My team started seeing CI builds fail when running `gosec` today, with no error output.

Our CI config installs `gosec` via `go get`, and thus gets the latest build from master.  After some sleuthing, I determined that `gosec` is taking ~10x as much memory (and, in development at least, 8x as much wall-time) vs. what it used to.

For our project (126 files, 13172 lines), `gosec` used to take 600-700MB (estimated based on testing on MacOS), and now it takes 5-6GB (again estimated via testing on MacOS).

### Steps to reproduce the behavior

In one terminal window, run:

```bash
while [ 1 ]; do ps auxwww | grep gose[c] | awk '{ print $6 }'; sleep 1; done
```

In another terminal window, check out the gosec code, and:

```bash
git checkout eaba99df373285a0724f4b8edc011c6ea2ef42cf
dep ensure && go build ./cmd/gosec/... && time ./gosec <some test project>
# check window with memory monitor running to find last sample...

git checkout 85d180848dbb8f86cba5d71bbbe06e1b40ce2705
dep ensure && go build ./cmd/gosec/... && time ./gosec <some test project>
# check window with memory monitor running to find last sample...
```

### gosec version

Commit 85d180848dbb8f86cba5d71bbbe06e1b40ce2705

### Go version (output of 'go version')

1.11.6

### Operating system / Environment

MacOS X Mojave, and Linux (whatever environment CircleCI provides)

### Expected behavior

`gosec` won't ravenously consume more memory than my puny little CI container has (4GB).

### Actual behavior

`gosec` ravenously consumes more memory than my puny little CI container has.

**Comment by MrJoy** [comment] 2019-04-26 00:41
For now we're working around this by doing a binary install of 1.3.0 in CI, so it's not a show-stopper issue for us -- yet.  I'd hate to have to disable `gosec` in CI, but I don't think I can convince the org to bump our CI instance above 4GB just because we want to use this one tool.

I know, from looking at the change that this issue is probably a bit out of scope for you, but if you're plugged into the development process of `golang.org/x/tools/go/packages` maybe you can raise issues with them about memory consumption (and slowness).  Alternatively, perhaps you can keep a smaller window of code in memory, checking each file/package then discarding the AST before moving on?

**Comment by ccojocar** [comment] 2019-04-26 07:33
@MrJoy As you already mentioned this is caused by the `golang.org/x/tools/go/packages`package which is known to have this issue in Go 1.11.x. Other tools has suffered from this as well. 

Do you set the `GO111MODULE=on`? My understanding from the bug description is that you are not using Go modules. Is this right? 

I think the memory consummation has quite improved in Go 1.12.4. I would give it a try.

**Comment by yurishkuro** [comment] 2019-04-26 17:41
I started seeing similar issue in github.com/jaegertracing/jaeger, Travis build fails with gosec running out of memory. We're using 1.12.1, but not go modules.

**Comment by MrJoy** [comment] 2019-04-26 17:44
We're not using go modules -- and not in any danger of switching until the ecosystem has settled down a bit.  I did not set `GO111MODULE=on` in this case.

I'll take a peek at 1.12.4, and let you know what I see.  Thanks!

**Comment by MrJoy** [comment] 2019-04-26 18:59
Ok, so I just installed Go 1.12.4, reinstalled gosec via `go get`, ran things, and...  It's still >5.5GB peak heap usage.

```
# In another window, start my loop to watch for gosec's heap...

eval "$(gimme 1.12.4)"
# from my project's root, which lives in my GOPATH
go get -u github.com/securego/gosec/cmd/gosec/...
gosec -quiet -nosec=false ./... # Takes absurd amount of memory...

GO111MODULE=on go get -u github.com/securego/gosec/cmd/gosec/... # Errors out

GO111MODULE=on go get -u github.com/securego/gosec # Doesn't install binary, does wind up creating a go.mod/go.sum for my project...

GO111MODULE=on go install github.com/securego/gosec/cmd/gosec/...
gosec -quiet -nosec=false ./... # Still takes absurd amount of memory, albeit _slightly_ less -- like 5GB instead of 5.5-6GB, which could just be sampling noise...
```

I thought that maybe the lingering vendor/ folder might be an issue, with go.mod/go.sum in place, so I nuked that and re-ran gosec.  No improvement.

**Comment by gcmurphy** [comment] 2019-04-26 19:18
cc/ @azihsoyn fyi

**Comment by gcmurphy** [comment] 2019-04-26 21:22
I've reproduced this and the following change to [main.go](https://github.com/securego/gosec/blob/master/cmd/gosec/main.go) results in significantly less memory consumption (as we only hold type check metadata for a single package per loop).  I think we need to rework the analyzer.Process loop to avoid this problem. 

```diff
@@ -319,8 +355,10 @@ func main() {
                buildTags = strings.Split(*flagBuildTags, ",")
        }
 
-       if err := analyzer.Process(buildTags, packages...); err != nil {
-               logger.Fatal(err)
+       for _, pkg := range packages {
+               if err := analyzer.Process(buildTags, pkg); err != nil {
+                       logger.Fatal(err)
+               }
        }
 ```


@ccojocar I'd like to get a fix for this included in the next release if possible.

**Closed** 2019-04-28 07:06 UTC
Labels: bug, priority:high
