### ISSUE TITLE
Support vgo packages (packages outside of gopath)

### ISSUE THREAD

**Issue by hehnope** [securego/gosec#258] opened 2018-10-28 17:52 UTC
### Summary 
I attempted to use `gosec` on a project that I've converted to `vgo`; note, these projects **must** be outside of the `GOPATH`; attempting to scan this project results in an error.

### Steps to reproduce the behavior
Convert a project to `vgo`, move it outside of the `GOPATH` (this is a requirement for go 1.11 unless you set `GO111MODULE=on`), then try to scan the project:

```
$ ./bin/gosec ~/Desktop/<project>/
[gosec] 2018/10/28 13:48:17 including rules: default
[gosec] 2018/10/28 13:48:17 excluding rules: default
2018/10/28 13:48:17 /home/a/Desktop/<project>/ is not within the $GOPATH and cannot be processed
```

### gosec version
Built from master today (no version is output):
```
VERSION: 
GIT TAG: 
BUILD DATE: 
```

### Go version (output of 'go version')
```
$ go version
go version go1.11.1 linux/amd64
```

### Operating system / Environment
```
64-bit Linux
```

### Expected behavior
I expect `gosec` to scan the project successfully even outside of the GOPATH.

### Actual behavior
`gosec` does not scan project because the project is not in the GOPATH.

**Comment by ccojocar** [comment] 2018-11-11 08:58
Duplicate of #234

**Closed by ccojocar** 2018-11-11 08:58 UTC
