### ISSUE TITLE
Panic occurs using latest gosec version

### ISSUE THREAD

**Issue by Kousik1612** [securego/gosec#928] opened 2023-02-09 03:48 UTC
### Summary 
Panic occurs using latest gosec
We are using gosec latest version 2.15.0 and we get panic when we use this
```
gosec -quiet -exclude=G104 ./...
460panic: runtime error: invalid memory address or nil pointer dereference
461[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x743221]
```

### Steps to reproduce the behavior

```
go install github.com/securego/gosec/v2/cmd/gosec@latest
gosec -quiet -exclude=G104 ./...
```

### gosec version
2.15.0

### Go version (output of 'go version')
```
go version
go version go1.20 darwin/amd64
```

### Operating system / Environment
Mac OS/ dev

### Expected behavior
should not panic

### Actual behavior
```
460panic: runtime error: invalid memory address or nil pointer dereference
461[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x743221]
```

**Comment by ccojocar** [comment] 2023-02-09 12:50
Somehow I cannot reproduce it on my side. Please could you provide the code sample you are running gosec against? Thanks

**Comment by ccojocar** [comment] 2023-02-14 13:25
Closing this because it cannot be reproduced. Please feel free to reopen it with more details and a sample code which can be used to generate the crash. Thanks

**Closed by ccojocar** 2023-02-14 13:25 UTC
Labels: bug
