### ISSUE TITLE
replace directive with relative path in go.mod confuses gosec

### ISSUE THREAD

**Issue by zabbal** [securego/gosec#588] opened 2021-03-17 10:19 UTC
### Summary 
When using gosec against multi-module project with 'replace' directive which uses relative file paths to redirect to a local copy of dependency the gosec fails with cryptic error.

### Steps to reproduce the behavior
Create go module with a dependency, place the dependency copy into local directory and add replace into go.mod as follows:

`replace lambdaOutput v0.0.0 => ./../lambdaOutput`

run `gosec ./...` as usual, it'll fail with unobvious "Golang errors in file" of `could not import lambdaOutput (invalid package name: "")`

### gosec version

Version: 2.7.0
Git tag: v2.7.0

### Go version (output of 'go version')

go version go1.14.6 gccgo (Ubuntu 10.2.0-13ubuntu1) 10.2.0 linux/amd64

### Operating system / Environment

Ubuntu 20.10

### Expected behavior

The scan proceeds properly resolving relative file paths. Or at least detects the situation and report this as an unsupported scan target.

### Actual behavior

Error message about failed import with invalid package name.

**Comment by ccojocar** [comment] 2021-03-17 10:32
Thanks for reporting this issues. Does the `go build` work with this project? Can you please provide an archive with the project layout and module file?

**Comment by zabbal** [comment] 2021-03-17 11:16
I'm trying to distill the minimal example but to no avail so far.

Here's how problematic go.mod looks like:
`
module testclient

go 1.14

require (
        github.com/aws/aws-sdk-go v1.37.32
        globals v0.0.0
)

replace globals v0.0.0 => ./../globals
`
I suspect that the problem is with the last line. When this module is located deeper in the fs like module/lambda/testclient the top-level scan in github-action with "gosec module/lambda/..." fails because it unable to resolve the relative "../globals" properly.

**Comment by ccojocar** [comment] 2021-03-17 13:47
Can you try to build that project with `go build` and using the same module file?

**Comment by ccojocar** [comment] 2021-03-21 08:40
Hi @zabbal, Is it possible to get more information to reproduce the issue? We can close it otherwise. Thanks!

**Comment by zabbal** [comment] 2021-03-22 14:19
Pardon the radio silence - I'm still far from eing proficient with golang and unfortunately I'm not at liberty to share actual code.

The problem boild down to following: if I `cd code/nested/location/go/` and than run either `go build` or `gosec ./...` than they succeed, the relative module dependencies are properly resolved. However if I run from top-level directory `gosec code/nested/location/go/...` it fails.

If there were some way to tell gosec's github action to cd into that directory before running gosec - that would be perfect.

**Comment by ccojocar** [comment] 2021-03-22 14:40
Do you have the `GOPATH` properly configured in the environment? Also does `go build code/nested/location/go/...` work?

 I think you issue is related to your Go setup, and it is not really in the gosec because. gosec relies on the same packages used by the `go build` to load the and parse the code.

**Comment by zabbal** [comment] 2021-03-22 15:07
Indeed, `go build code/nested/location/go/...` fails with complaints about "cannot find package". Seems like I'm missing smth very basic.

Shall I try setting $GOROOT to the top-level directory? Or $GOPATH? I've assumde that github-action does that already. Is there some clarifying docs I could read?

**Comment by ccojocar** [comment] 2021-03-22 15:21
This is the only documentation we have that is related to the Github action https://github.com/securego/gosec#github-action. The Go environment variables are configured by the golang base image form hhttps://github.com/securego/gosec/blob/master/Dockerfile. 

I am closing this issue since is not related to gosec. Thanks!

**Closed by ccojocar** 2021-03-22 15:21 UTC
Labels: question
