### ISSUE TITLE
Local install fails with error

### ISSUE THREAD

**Issue by jmwohl** [securego/gosec#411] opened 2019-11-01 00:57 UTC
### Summary 
When attempting to install package locally as specified in the README with `go get github.com/securego/gosec/cmd/gosec` the install fails with error.

### Steps to reproduce the behavior
Run `go get github.com/securego/gosec/cmd/gosec`

### gosec version
Latest from master

### Go version (output of 'go version')
go1.12.10 darwin/amd64

### Operating system / Environment
OSX Mavericks

### Expected behavior
Package installs

### Actual behavior
The install fails with the following error:

```
# github.com/securego/gosec
securego/gosec/analyzer.go:37:7: const initializer packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedImports | packages.NeedTypes | packages.NeedTypesSizes | packages.NeedTypesInfo | packages.NeedSyntax is not a constant
securego/gosec/analyzer.go:37:18: undefined: packages.NeedName
securego/gosec/analyzer.go:38:2: undefined: packages.NeedFiles
securego/gosec/analyzer.go:39:2: undefined: packages.NeedCompiledGoFiles
securego/gosec/analyzer.go:40:2: undefined: packages.NeedImports
securego/gosec/analyzer.go:41:2: undefined: packages.NeedTypes
securego/gosec/analyzer.go:42:2: undefined: packages.NeedTypesSizes
securego/gosec/analyzer.go:43:2: undefined: packages.NeedTypesInfo
securego/gosec/analyzer.go:44:2: undefined: packages.NeedSyntax
```

**Comment by ccojocar** [comment] 2019-11-01 08:27
Do you have the Go module turned on - `export GO111MODULE=on`? 

It seems to work for me when Go module is enabled:

```
$ go version
go version go1.12.10 darwin/amd64
$ go get github.com/securego/gosec/cmd/gosec
go: finding github.com/securego/gosec/cmd/gosec latest
go: finding github.com/securego/gosec/cmd latest
go: finding github.com/securego/gosec latest
go: downloading github.com/securego/gosec v0.0.0-20191031105617-99170e0d765b
go: extracting github.com/securego/gosec v0.0.0-20191031105617-99170e0d765b
```

**Comment by ccojocar** [comment] 2019-11-18 09:02
I am going to close this since I am not able to reproduce it. Thanks!

**Closed by ccojocar** 2019-11-18 09:02 UTC
